<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
	'Access denied.' => 'Нямате достъп.',
	'Add' => 'Добави',
	'Add child' => 'Добави наследник',
	'Add {type}' => 'Добави {type}',
	'Ancestors' => 'Предшественици',
	'Are you sure you want to delete this item?' => 'Сигурни ли сте, че искате да изтриете този елемент?',
	'Assign' => 'Възложи',
	'Assign permission' => 'Възложи право',
	'Assigned items' => 'Възложи елементи',
	'Assignments' => 'Назначения',
	'Business rule' => 'Бизнес правило',
	'Cancel' => 'Отмени',
	'Create' => 'Създай',
	'Delete' => 'Изтрий',
	'Data' => 'Данни',
	'Descendants' => 'Наследници',
	'Description' => 'Описание',
	'Edit' => 'Редактирай',
	'Invalid request.' => 'Невалидна заявка.',
	'Item does not exist.' => 'Елемента не существува.',
	'Items' => 'Елементи',
	'Items assigned to this user' => 'Елементи, възложени на този потребител',
	'New {type}' => 'Нов {type}',
	'No assignments found.' => 'Няма намерени възложения',
	'No {type} found.' => 'Няма намерени {type}',
	'Page not found.' => 'Страница не съществува',
	'Permissions' => 'Права',
	'Permissions granted by this item' => 'Права, предоставени от този елемент',
	'Permissions that inherit this item' => 'Права, наследили този елемент',
	'Remove' => 'Изтрий',
	'Revoke' => 'Отнеми',
	'Save' => 'Съхрани',
	'Select item' => 'Избери елемент',
	'System name' => 'Системно име',
	'System name cannot be changed after creation.' => 'Системното име не може да бъде редактирано след създаването му',
	'This item does not have any ancestors.' => 'Този елемент няма предшественици',
	'This item does not have any descendants.' => 'Този елемент няма наследници',
	'This user does not have any assignments.' => 'Този потребител няма права',
	'Type' => 'Тип',
	'User' => 'Потребител',
	'View' => 'Преглед',
	'operation|operations' => 'операция|операции',
	'role|roles' => 'роля|роли',
	'task|tasks' => 'задача|задачи',
);
